### ISSUE TITLE
Build possibilities for ncl

### ISSUE THREAD

**Issue by cdesjardins** [mtholder/ncl#13]
Hello, I am working with @mbrazeau on a program called morphy that uses ncl, I put a copy of it in [github ](https://github.com/cdesjardins/ncl) a while ago now and it works great. Lately however we have been doing some rework and expanding to new platforms (i.e. windows). In order to support this I have been using cmake to build everything. In ncl however the issue is that you use the rather old auto-tools on posix and just have a msvc project file for windows (which in my version at least was missing some files, and had different include paths for debug and release, and other minor things that were broken). This works but is not great; obviously there are maintenance issues. I think for a lib like ncl it would be rather trivial to add some cmake files and get rid of your current build systems and support all major platforms and all version of msvc, xcode, eclipse, make, etc... My question is would you be willing to accept a pull request with such a change? If so I will put that together for you.

**Comment by mtholder** [comment]
Watch it! I'm older than auto-tools.

In all seriousness, yes, we'd be happy to accept a cmake project. Though I don't want to get rid of the autotools functionality (because some NCL-dependent libraries have scripts that build NCL using those tools).

**Comment by cdesjardins** [comment]
Don't worry I am a solid 20 years older than autotools... Anyhow this is great, what about the vc7 and xcode dirs? Would you be ok if they were done away with?

**Comment by cdesjardins** [comment]
OK, I created the cmakefiles at https://github.com/cdesjardins/ncl on the cmake branch, my code isn't forked from yours so it isn't letting me do a pull request just yet. I will have to make a fork and sort it out later, as I am about to head out for the day. But you can at least look at it now if you like.

**Comment by mtholder** [comment]
looks good to me, thanks.

**Comment by cdesjardins** [comment]
Not sure if you got the notification but my pull request is still waiting to be merged: https://github.com/mtholder/ncl/pull/14

Thanks.

**Comment by mtholder** [comment]
Sorry for the delay, and thanks for the PR.
